import constants
CURRENT_FILE_PREFIX = 'Current file: '
TARGET_FOUNDED = f'Target file exists: [{constants.target_path}]. '
ERROR_FILE_NOT_FOUND = 'ERROR! File not found. '
NO_MORE_PARTS = 'End search for parts. No more parts. '
CONTENT_INCOMPLETED = 'Something not matched. Content has some problem. '
INTERVAL_NOT_EXIST = 'The interval does not exist. '
NO_MORE_ITEM = 'End search for items. No more items. '
ERROR_NO_NONNEGATIVE_VALUE = 'ERROR! No value is NON-NEGATIVE. '
INFO_NOT_MOD = 'The infotype is not \'mods\'. '
CREATE_MODINFO = 'ModInfo instance is created. '
VALUETYPE_ERROR = 'Not expected value type found. '
MEET_PURE_END = 'Meet a \'pure\' end, no \'\\r\' or \'\\n\'. '
ON_THE_RIGHT = ': on the right side. '
ON_THE_LEFT = ': on the left side. '